### ISSUE TITLE
TypeError on install during ruby build

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#186]
I'm trying to get a local install running on my machine. I've been following instructions in https://github.com/zooniverse/Galaxy-Zoo/blob/76558a15997bc9a3d8389df7bb0b5e274cea59b0/README.md 

```
[willettk@x-131-212-237-85 Galaxy-Zoo]$ npm install .
npm WARN package.json node-pubsub@0.1.0 No repository field.
npm WARN engine stylus@0.23.0: wanted: {"node":"> 0.4.x < 0.7.0"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine stylus@0.23.0: wanted: {"node":"> 0.4.x < 0.7.0"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine stylus@0.23.0: wanted: {"node":"> 0.4.x < 0.7.0"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine express@2.5.0: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine connect@1.7.3: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"0.12.0","npm":"2.5.1"})
jasmine-phantom-node@0.1.0 node_modules/jasmine-phantom-node
├── ansi-color@0.2.1
└── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)

hem@0.1.9 node_modules/hem
├── watch@0.4.0
├── optimist@0.2.8 (wordwrap@0.0.2)
├── eco@1.1.0-rc-3 (strscan@1.0.1)
├── coffee-script@1.3.3
├── fast-detective@0.0.2 (burrito@0.2.12)
├── stylus@0.23.0 (growl@1.1.0, mkdirp@0.0.7, cssom@0.2.1)
└── strata@0.15.1 (usererror@1.0.2, strftime@0.4.6, bufferedstream@1.0.2, mime@1.2.3, markdown@0.3.1)

zooniverse@0.0.1 node_modules/zooniverse
├── eco@1.1.0-rc-3 (strscan@1.0.1)
└── hem@0.1.9 (watch@0.4.0, optimist@0.2.8, coffee-script@1.3.3, uglify-js@1.1.1, fast-detective@0.0.2, stylus@0.23.0, strata@0.15.1)

ubret@0.0.1 node_modules/ubret
├── serveup@0.0.5 (optimist@0.2.8, express@2.5.0)
├── zooniverse@0.7.3
└── hem@0.1.9 (watch@0.4.0, optimist@0.2.8, eco@1.1.0-rc-3, coffee-script@1.3.3, fast-detective@0.0.2, uglify-js@1.1.1, stylus@0.23.0, strata@0.15.1)

[willettk@x-131-212-237-85 Galaxy-Zoo]$ ./fits/build.rb 
/Users/willettk/Astronomy/Research/GalaxyZoo/Galaxy-Zoo/node_modules/hem/bin/hem:6
if (path.existsSync('./slug.js')) {
         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/willettk/Astronomy/Research/GalaxyZoo/Galaxy-Zoo/node_modules/hem/bin/hem:6:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
mv: public/application.js: No such file or directory
rm: public/application.css: No such file or directory
```

I've referred back to #173, which was on the ```starburst``` branch, but am not getting the same messages I did then. Any ideas you might have, @parrish or @chrissnyder?

**Comment by edpaget** [comment]
@willettk what's the result of running `node version`

**Comment by edpaget** [comment]
It looks like the `path.existsSync` function was removed in node 0.12 after being deprecated in 0.8.

**Comment by willettk** [comment]
[willettk@x-131-212-237-85 Galaxy-Zoo]$ node -v

v0.12.0

**Comment by chrissnyder** [comment]
Yea, I'd recommend you use nvm to switch to node version ~0.10.x. I imagine there are updated dependencies that have corrected this issue, but I'd rather not touch those unless absolutely necessary.

**Comment by willettk** [comment]
nvm and node 0.10.36 work on all the builds. Might be worth adding a note
to the README.md file.

Thanks!

close #186
